# Form implementation generated from reading ui file 'assigment_grader.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Grader(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Grader")
        Dialog.resize(240, 320)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(70, 10, 111, 20))
        self.label.setObjectName("label")
        self.student_line = QtWidgets.QLineEdit(parent=Dialog)
        self.student_line.setGeometry(QtCore.QRect(110, 40, 121, 21))
        self.student_line.setObjectName("student_line")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 101, 20))
        self.label_2.setObjectName("label_2")
        self.grade_line = QtWidgets.QLineEdit(parent=Dialog)
        self.grade_line.setGeometry(QtCore.QRect(110, 80, 121, 21))
        self.grade_line.setObjectName("grade_line")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 101, 111))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.calculate_button = QtWidgets.QPushButton(parent=Dialog)
        self.calculate_button.setGeometry(QtCore.QRect(0, 250, 131, 51))
        self.calculate_button.setObjectName("calculate_button")
        self.output_box = QtWidgets.QTextEdit(parent=Dialog)
        self.output_box.setGeometry(QtCore.QRect(40, 140, 171, 101))
        self.output_box.setObjectName("output_box")
        self.export_button = QtWidgets.QPushButton(parent=Dialog)
        self.export_button.setGeometry(QtCore.QRect(130, 250, 111, 51))
        self.export_button.setObjectName("export_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Assigment grader"))
        self.label_2.setText(_translate("Dialog", "Input class size"))
        self.label_3.setText(_translate("Dialog", "Enter all student scores with a space inbetween"))
        self.calculate_button.setText(_translate("Dialog", "calculate grades"))
        self.export_button.setText(_translate("Dialog", "Export grades"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Grader()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
